---
title: Nikolay's Software Notes
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: post
    permalink: "/posts/:title/"
- scope:
    path: ''
    type: pages
  values:
    layout: page
description: Software notes
github_repo: softnotes
github_username: nikolayhg
theme_color: light
remote_theme: broccolini/athena
permalink: pretty
markdown: kramdown
